experiment: MujocoHopper
timestamp: True
new_model: True
experiment_config:
  agent: "RGRN"
  agent_kwargs:
    num_hidden: 16
    num_layers: 1
  world_kwargs:
    n_episodes: 8
    log_fields: ["reward", "done", "observation"]
es: CMAES
generations: 500
es_config:
  popsize: 128
  weight_decay: 0.001                # L2 weight decay for the parameters of the evolutionary strategy (NOT of the diffusion model)
  sigma_init: 0.5
  inopts:
    CMA_elitist: 1
